const GEO_ENTRIES = [
  ['AD', 'Andorra'],
  ['AE', 'United Arab Emirates'],
  ['AF', 'Afghanistan'],
  ['AL', 'Albania'],
  ['AM', 'Armenia'],
  ['AO', 'Angola'],
  ['AR', 'Argentina'],
  ['AT', 'Austria'],
  ['AU', 'Australia'],
  ['AZ', 'Azerbaijan'],
  ['BA', 'Bosnia and Herzegovina'],
  ['BD', 'Bangladesh'],
  ['BE', 'Belgium'],
  ['BG', 'Bulgaria'],
  ['BH', 'Bahrain'],
  ['BO', 'Bolivia'],
  ['BR', 'Brazil'],
  ['BY', 'Belarus'],
  ['CA', 'Canada'],
  ['CH', 'Switzerland'],
  ['CL', 'Chile'],
  ['CN', 'China'],
  ['CO', 'Colombia'],
  ['CR', 'Costa Rica'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czechia'],
  ['DE', 'Germany'],
  ['DK', 'Denmark'],
  ['DO', 'Dominican Republic'],
  ['DZ', 'Algeria'],
  ['EC', 'Ecuador'],
  ['EE', 'Estonia'],
  ['EG', 'Egypt'],
  ['ES', 'Spain'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GB', 'United Kingdom'],
  ['GE', 'Georgia'],
  ['GH', 'Ghana'],
  ['GR', 'Greece'],
  ['GT', 'Guatemala'],
  ['HK', 'Hong Kong'],
  ['HR', 'Croatia'],
  ['HU', 'Hungary'],
  ['ID', 'Indonesia'],
  ['IE', 'Ireland'],
  ['IL', 'Israel'],
  ['IN', 'India'],
  ['IQ', 'Iraq'],
  ['IR', 'Iran'],
  ['IS', 'Iceland'],
  ['IT', 'Italy'],
  ['JO', 'Jordan'],
  ['JP', 'Japan'],
  ['KE', 'Kenya'],
  ['KG', 'Kyrgyzstan'],
  ['KR', 'South Korea'],
  ['KW', 'Kuwait'],
  ['KZ', 'Kazakhstan'],
  ['LB', 'Lebanon'],
  ['LK', 'Sri Lanka'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['LV', 'Latvia'],
  ['MA', 'Morocco'],
  ['MD', 'Moldova'],
  ['ME', 'Montenegro'],
  ['MK', 'North Macedonia'],
  ['MX', 'Mexico'],
  ['MY', 'Malaysia'],
  ['NG', 'Nigeria'],
  ['NL', 'Netherlands'],
  ['NO', 'Norway'],
  ['NP', 'Nepal'],
  ['NZ', 'New Zealand'],
  ['OM', 'Oman'],
  ['PA', 'Panama'],
  ['PE', 'Peru'],
  ['PH', 'Philippines'],
  ['PK', 'Pakistan'],
  ['PL', 'Poland'],
  ['PR', 'Puerto Rico'],
  ['PT', 'Portugal'],
  ['PY', 'Paraguay'],
  ['QA', 'Qatar'],
  ['RO', 'Romania'],
  ['RS', 'Serbia'],
  ['RU', 'Russia'],
  ['SA', 'Saudi Arabia'],
  ['SE', 'Sweden'],
  ['SG', 'Singapore'],
  ['SI', 'Slovenia'],
  ['SK', 'Slovakia'],
  ['TH', 'Thailand'],
  ['TJ', 'Tajikistan'],
  ['TN', 'Tunisia'],
  ['TR', 'Turkey'],
  ['TW', 'Taiwan'],
  ['UA', 'Ukraine'],
  ['US', 'United States'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VE', 'Venezuela'],
  ['VN', 'Vietnam'],
  ['ZA', 'South Africa'],
];

const GEO_NAMES = Object.fromEntries(GEO_ENTRIES);
const GEO_CODES = GEO_ENTRIES.map(([code]) => code);
const GEO_FLAG_CODES = Object.fromEntries(GEO_CODES.map((code) => [code, code.toLowerCase()]));

function isKnownGeo(value) {
  if (!value || typeof value !== 'string') return false;
  return Object.prototype.hasOwnProperty.call(GEO_NAMES, value.trim().toUpperCase());
}

module.exports = {
  GEO_ENTRIES,
  GEO_NAMES,
  GEO_CODES,
  GEO_FLAG_CODES,
  isKnownGeo,
};
